import = [
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "DejaVuSansM Nerd Font", style = "Regular" }
bold = { family = "DejaVuSansM Nerd Font", style = "Bold" }
italic = { family = "DejaVuSansM Nerd Font", style = "Italic" }
bold_italic = { family = "DejaVuSansM Nerd Font", style = "Bold Italic" }

size = 20
