general.import = [
    "~/.config/alacritty/themes/deus_default.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Terminess Nerd Font", style = "Regular" }
bold = { family = "Terminess Nerd Font", style = "Bold" }
italic = { family = "Terminess Nerd Font", style = "Italic" }
bold_italic = { family = "Terminess Nerd Font", style = "Bold Italic" }

size = 20

[window]
opacity = 0.7
padding = { x = 15, y = 5}
